version: '3.8'
services:
  database:
    image: mydatabase
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: s09_a202_mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
      - mosquitto
    networks:
      - bridge-network
      - was-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  spring-boot:
    image: myspring
    container_name: spring-boot
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    networks:
      - was-network
    restart: unless-stopped

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 4000:5173
    restart: unless-stopped

  nginx:  # Nginx Container
    image: nginx
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./etc/nginx:/etc/nginx/conf.d
     - /etc/letsencrypt:/etc/letsencrypt
   restart: unless-stopped

networks:
  bridge-network:
    driver: bridge
  was-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mysql-data:
  cert-conf:


