spring:
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  datasource:
    username: root
    password: root
    url: jdbc:mariadb://j9a307.p.ssafy.io:3306/dubu
    driver-class-name: org.mariadb.jdbc.Driver

#  sql:
#    init:
#      mode: never

server:
  port: 8080

  # Security OAuth
  security:
    oauth2.client:
      registration:
        kakao:
          clientId: '995b853d363b375b49707e2b7a258f34'
          clientSecret: '- QZJGoxrgVg3ctIhGiZ6GoWCdJWNArput'
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8080/login/oauth2/code/kakao"
          scope:
            - profile_nickname
            - profile_image
          clientName: Kakao
      # Provider 설정
      provider:
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect